feat: include the git remote prune origin step into the command
oat-sa/tao-extension-release pull request #75
Opened 2022-06-30 13:07 UTC by taorafael

Recently we've had a bug when trying to release a new version.

The problem was that when @SergiiTao was instructing me on how to make a release, the cached index of remote branches still pointed to a release branch we had deleted a few minutes ago.

Since this is an automated tool, pruning the remote branches shouldn't be considered too big an effort and it might help avoiding similar problems in the future

2022-06-30 13:53 UTC, bugalot requested changes
Hello @taorafael !

Usually, when we create a TAO Extension PR, the base branch is `develop`. It looks good to me! Let's see what the owner of the extension thinks about it!

@krampstudio , what's your opinion?

2022-06-30 13:56 UTC, taorafael commented
I will change the destination of the PR then :)
And check if there's a changelog, I usually forget to update those.

2022-06-30 14:36 UTC, taorafael commented
> > Hello @taorafael !
> > Usually, when we create a TAO Extension PR, the base branch is `develop`. It looks good to me! Let's see what the owner of the extension thinks about it!
> > @krampstudio , what's your opinion?
> 
> yes, by default we try to keep the some branching model. And you will be able to release this repo with itself, from the `develop` branch exploding_head

No prob, I've already changed the direction of the PR to point to **develop** instead of master :)

2022-07-01 12:34 UTC, jsconan reviewed
The code looks straightforward, so I have nothing to say about it.

I need to test it in a real situation, so I'll wait a bit before approving. For the time being, I will use this branch for my local installation of the tool.

2022-07-05 07:29 UTC, krampstudio approved these changes
Evreything looks good from my side.
I was able to test it on an npm release:
![image](https://user-images.githubusercontent.com/468620/177273755-39008c40-d65e-46d4-a419-ba2dbf5c444c.png)

Good job :rocket:

2022-07-05 07:43 UTC, taorafael commented
> Evreything looks good from my side. I was able to test it on an npm release
> Good job rocket

Now I wonder if I should have left the passed as 'ok' :sweat_smile:, too late now I guess

2022-07-05 10:41 UTC, taorafael commented on src/release.js
> +            log.done(`Remote branches pruned`);
```suggestion
            log.done('Remote branches pruned');
```

2022-07-05 11:01 UTC, bugalot approved these changes

2022-07-12 13:14 UTC, jsconan approved these changes
LGTM. Good job!

2022-09-08 07:21 UTC, oatymart commented
I've been using this version for a few releases - I'm going to merge it.

2022-09-08 07:25 UTC, merged